// swift-tools-version: 5.7
// Generated by digilocker-ios-sdk-dev/.github/workflows/release.yml.
// Do not edit by hand: the checksum must match the asset on release v1.0.0.

import PackageDescription

let package = Package(
    name: "DigilockerSDK",
    platforms: [
        .iOS(.v15)
    ],
    products: [
        .library(
            name: "DigilockerSDK",
            targets: ["DigilockerSDK"])
    ],
    targets: [
        .binaryTarget(
            name: "DigilockerSDK",
            url: "https://github.com/surepassio/digilocker-ios-binary/releases/download/v1.0.0/DigilockerSDK.xcframework.zip",
            checksum: "0b7d665eee9502f836ab02dd6f716c5e30e0153921542e79de75d47c14e86cb2"
        )
    ]
)
